Front rating updated
lv487nodejs/NChoice_client_fe pull request #349
Opened 2020-05-25 19:07 UTC by bandvov

2020-05-27 12:12 UTC, oleksandrhodzevych requested changes

2020-05-27 12:12 UTC, oleksandrhodzevych commented on client/src/components/comment-form/comment-form.js
> +      <div className='star'><h6 className='rate'> Rate the product: </h6> <StarsRating rating={rate} id={productId} userId={userId} readonly={false} color="black" isSelectable={true}/></div>
move to next row

2020-05-27 12:12 UTC, oleksandrhodzevych commented on client/src/components/comment-form/comment-form.js
> +      <div className='star'><h6 className='rate'> Rate the product: </h6> <StarsRating rating={rate} id={productId} userId={userId} readonly={false} color="black" isSelectable={true}/></div>
color="black" - hard code

2020-05-27 12:12 UTC, oleksandrhodzevych commented on client/src/components/product-details/Product-details.js
> +          <StarsRating rating={product.rate} color="black" isSelectable={false} />
color="black" - hard code

2020-05-27 12:12 UTC, oleksandrhodzevych commented on client/src/components/product-list-item/Product-list-item.js
> +                        <StarsRating rating={rate} color="white" isSelectable={false} />
color="white" - hard code

2020-05-27 12:12 UTC, oleksandrhodzevych commented on client/src/components/star-rating/Star-rating.js
> +        numberOfStars={5}
numberOfStars={5} - hard code

2020-05-27 12:12 UTC, oleksandrhodzevych commented on client/src/components/star-rating/Star-rating.js
> +        starDimension="25px"
starDimension="25px" - hard code

2020-05-28 07:59 UTC, bandvov commented on client/src/components/comment-form/comment-form.js
> +      <div className='star'><h6 className='rate'> Rate the product: </h6> <StarsRating rating={rate} id={productId} userId={userId} readonly={false} color="black" isSelectable={true}/></div>
fixed

2020-05-28 07:59 UTC, bandvov commented on client/src/components/comment-form/comment-form.js
> +      <div className='star'><h6 className='rate'> Rate the product: </h6> <StarsRating rating={rate} id={productId} userId={userId} readonly={false} color="black" isSelectable={true}/></div>
fixed

2020-05-28 08:16 UTC, bandvov commented on client/src/components/product-details/Product-details.js
> +          <StarsRating rating={product.rate} color="black" isSelectable={false} />
fixed

2020-05-28 08:19 UTC, bandvov commented on client/src/components/product-list-item/Product-list-item.js
> +                        <StarsRating rating={rate} color="white" isSelectable={false} />
fixed

2020-05-28 08:21 UTC, bandvov commented on client/src/components/star-rating/Star-rating.js
> +        numberOfStars={5}
fixed

2020-05-28 08:21 UTC, bandvov commented on client/src/components/star-rating/Star-rating.js
> +        starDimension="25px"
fixed

2020-05-28 08:41 UTC, merged