task #314
lv487nodejs/NChoice_client_fe pull request #378
Opened 2020-06-01 09:52 UTC by chak-kit

2020-06-03 13:56 UTC, VolodymyrTrach requested changes

2020-06-03 13:56 UTC, VolodymyrTrach commented on client/src/components/app-footer/App-footer.js
> +      <Link className='footer-icon' to={socialNetworksURL.facebook} target='_blank'>
already changed at footer branch

2020-06-03 13:56 UTC, VolodymyrTrach commented on client/src/components/comment-form/comment-form.js
> +          reviewerName={comment.user.firstName || "Anonym"}
remove hardcode "Anonym" to 
const anonim = "Anonim" than use 
reviewerName={comment.user.firstName || anonim}

2020-06-03 15:09 UTC, bandvov approved these changes

2020-06-03 20:40 UTC, VolodymyrTrach commented
fix the dropdown menu at the left header. there are no catalogs now

2020-06-04 05:11 UTC, bandvov approved these changes

2020-06-04 09:01 UTC, merged